[package]
name = "sunshine-client"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[features]
light = [
    "sc-service",
    "sled",
    "sp-database",
    "substrate-subxt/client",
    "sunshine-node",
    "thiserror",
]

[dependencies]
client-faucet = { path = "../../sunshine-identity/faucet/client" }
client-identity = { path = "../../sunshine-identity/identity/client" }
sled = { version = "0.32.0", optional = true }
sc-service = { version = "0.8.0-rc4", optional = true }
sp-database = { version = "2.0.0-rc4", optional = true }
substrate-subxt = { version = "0.10.1", features = ["client"] }
sunshine-node = { path = "../node", optional = true }
thiserror = { version = "1.0.20", optional = true }
utils-identity = { path = "../../sunshine-identity/identity/utils" }
