[package]
name = "sunshine-client"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[features]
light = [
    "sc-service",
    "sp-database",
    "substrate-subxt/client",
    "sunshine-node",
]

[dependencies]
ipfs-embed = "0.1.1"
keybase-keystore = "0.1.0"
sled = "0.32.0"
sc-service = { version = "0.8.0-rc4", optional = true, default-features = false }
sp-database = { version = "2.0.0-rc4", optional = true }
substrate-subxt = { version = "0.10.1", features = ["client"] }
sunshine-node = { version = "0.1.0", path = "../node", optional = true }
sunshine-faucet-client = "0.1.0"
sunshine-identity-client = "0.1.0"
sunshine-identity-utils = "0.1.0"
sunshine-util = { version = "0.0.6", default-features=false}
sunshine-org = { version = "0.0.6", default-features=false }
sunshine-vote = { version = "0.0.6", default-features=false}
sunshine-court = { version = "0.0.6", default-features=false}
sunshine-donate = { version = "0.0.6", default-features=false}
sunshine-bank = { version = "0.0.6", default-features=false}
sunshine-bounty = { version = "0.0.6", default-features=false}
thiserror = "1.0.20"
