[workspace]
members = [
    "bot",
    "cli",
    "client",
    "node",
    "runtime",
]

[patch.crates-io]
substrate-subxt = { git = "https://github.com/dvc94ch/substrate-subxt", branch = "different-assert" }

